name = "algorithm-guessr"
main = "src/worker.ts"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

[vars]
JWT_SECRET = "change-me-in-production"

[[kv_namespaces]]
binding = "PROBLEM_CACHE"
id = "" # 填入实际 KV 命名空间 ID
preview_id = ""

[[d1_databases]]
binding = "DB"
database_name = "algorithm_guessr_db"
database_id = "" # 填入实际数据库 ID
